---
- name: Homeserver Setup
  hosts: all
  gather_facts: false
  tasks:
    - name: Install Base
      ansible.builtin.include_role:
        name: collinsapps.homeserver.system
        tasks_from: main.yml
    - name: Install Services
      ansible.builtin.include_role:
        name: collinsapps.homeserver.system
        tasks_from: services.yml
