apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: homeserver-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: homeserver-issuer-account-key
    solvers:
    - http01:
       ingress:
         class: traefik 
